=== w3c/Unicorn/WebContent/WEB-INF/resources/schemas/tasklist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.w3.org/unicorn/tasklist" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tas="http://www.w3.org/unicorn/tasklist">
  <xs:element name="tasklist" type="tas:tasklistType" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
  <xs:complexType name="parametersType">
    <xs:sequence>
      <xs:element type="tas:parameterType" name="parameter" maxOccurs="unbounded" minOccurs="0" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="taskType">
    <xs:all>
      <xs:element type="tas:condsType" name="conds" xmlns:tas="http://www.w3.org/unicorn/tasklist" minOccurs="0" />
      <xs:element type="tas:routineType" name="routine" xmlns:tas="http://www.w3.org/unicorn/tasklist" />
      <xs:element type="tas:outputType" name="output" xmlns:tas="http://www.w3.org/unicorn/tasklist" />
      <xs:element type="tas:parametersType" name="parameters" xmlns:tas="http://www.w3.org/unicorn/tasklist" minOccurs="0" />
    </xs:all>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="default" use="optional"/>
  </xs:complexType>
  <xs:complexType name="parameterType" mixed="true">
    <xs:sequence>
      <xs:element type="tas:valueType" name="value" minOccurs="0" maxOccurs="unbounded" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
    </xs:sequence>
    <xs:attribute type="xs:NCName" name="name" use="required"/>
    <xs:attribute type="tas:tParamType" name="type" use="required"/>
    <xs:attribute type="xs:string" name="default" use="optional"/>
    <xs:attribute type="tas:tUi" name="ui" use="optional" default="advanced"/>
    <xs:attribute type="xs:NCName" name="observer" use="optional"/>
  </xs:complexType>
  <xs:complexType name="valueType">
    <xs:sequence>
      <xs:element type="tas:mappedType" name="mapped" maxOccurs="unbounded" minOccurs="0" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
  </xs:complexType>
  <xs:complexType name="outputType">
    <xs:sequence>

            <xs:element name="group" type="tas:groupType" minOccurs="0" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="paramType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:NCName" name="name"/>
        <xs:attribute type="xs:NCName" name="observer"/>
        <xs:attribute type="xs:string" name="value"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="condType">
  	<xs:sequence>
  		<xs:element name="value" type="xs:string" minOccurs="1"
  			maxOccurs="1" />
  	</xs:sequence>
  	<xs:attribute type="xs:string" name="id" use="optional" />
  	<xs:attribute type="xs:string" name="result" use="optional" />
  	<xs:attribute type="xs:NCName" name="observer" use="optional" />
  	<xs:attribute name="type" use="optional">
  		<xs:simpleType>
  			<xs:restriction base="xs:string">
  				<xs:enumeration value="parameter"></xs:enumeration>
  				<xs:enumeration value="xpath"></xs:enumeration>
  				<xs:enumeration value="mimetype"></xs:enumeration>
  				<xs:enumeration value="method"></xs:enumeration>
  			</xs:restriction>
  		</xs:simpleType>
  	</xs:attribute>
  	<xs:attribute name="parameter" type="xs:string" use="optional"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="routineType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element type="tas:ifType" name="if" maxOccurs="unbounded" minOccurs="0" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
      <xs:element type="tas:execType" name="exec" maxOccurs="unbounded" minOccurs="0" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ref"/>
  </xs:complexType>
  <xs:complexType name="ifType">
    <xs:sequence>
      <xs:element type="tas:routineType" name="then" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
      <xs:element type="tas:routineType" name="else" maxOccurs="1" minOccurs="0" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="test"/>
  </xs:complexType>
  <xs:complexType name="tasklistType">
    <xs:sequence>
      <xs:element type="tas:taskType" name="task" maxOccurs="unbounded" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mappedType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:NCName" name="param" use="required"/>
        <xs:attribute type="xs:NCName" name="observer" use="required"/>
        <xs:attribute type="xs:string" name="value"/>
	<xs:attribute name="inputmethod" use="optional" default="uri direct file">
                <xs:simpleType>
                    <xs:list itemType="tas:tInputMethod"/>
                </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="condsType">
    <xs:sequence>
      <xs:element type="tas:condType" name="cond" maxOccurs="unbounded" minOccurs="1" xmlns:tas="http://www.w3.org/unicorn/tasklist"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="execType" mixed="true">
  	<xs:sequence>
  		<xs:element type="tas:paramType" name="param" minOccurs="0"
  			xmlns:tas="http://www.w3.org/unicorn/tasklist" />
  	</xs:sequence>

  	<xs:attribute type="xs:string" name="value" use="optional" />
  	<xs:attribute type="xs:string" name="type" use="optional" />

  	<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
  </xs:complexType>
  <xs:simpleType name="tInputMethod" xmlns:tas="http://www.w3.org/unicorn/tasklist">
        <xs:restriction base="xs:string">
            <xs:enumeration value="file"/>
            <xs:enumeration value="direct"/>
            <xs:enumeration value="uri"/>
        </xs:restriction>     
    </xs:simpleType>
    <xs:simpleType name="tUi" xmlns:tas="http://www.w3.org/unicorn/tasklist">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="simple"/>
            <xs:enumeration value="advanced"/>
        </xs:restriction>     
    </xs:simpleType>
    <xs:simpleType name="tParamType" xmlns:tas="http://www.w3.org/unicorn/tasklist">
        <xs:restriction base="xs:string">
            <xs:enumeration value="checkbox"/>
            <xs:enumeration value="checkboxlist"/>
            <xs:enumeration value="dropdown"/>
            <xs:enumeration value="dropdownlist"/>
            <xs:enumeration value="textarea"/>
            <xs:enumeration value="textfield"/>
            <xs:enumeration value="radio"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="groupType">
    	<xs:sequence>
    		<xs:element name="observation" type="xs:string" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="type" use="optional">
    		<xs:simpleType>
    			<xs:restriction base="xs:string">
    				<xs:enumeration value="firstPassed"></xs:enumeration>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    </xs:complexType>
</xs:schema>

=== w3c/Unicorn/WebContent/WEB-INF/resources/tasklist/tasklist.xml
<?xml version="1.0" ?>
<tasklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/unicorn/tasklist ../schemas/tasklist.xsd"
	xmlns="http://www.w3.org/unicorn/tasklist">

	<task id="conformance" default="true">

		<routine>
			<exec id="markup-validator" value="markup-validator" type="observation" />
			<exec id="css2" value="css2-validator" type="observation" />
			<exec id="css21" value="css21-validator" type="observation" />
			<exec id="css3" value="css3-validator" type="observation" />
			<exec id="css1" value="css1-validator" type="observation" />
			<exec id="feed" value="feed" type="observation" />
		</routine>

		<parameters>
			<!-- <parameter name="profile" default="css21" ui="simple" type="dropdown" observer="css-validator"/> -->
			<parameter name="warning" ui="none" type="dropdown" default="all">
				<value name="all">
					<mapped param="warning" observer="css21-validator" value="2" />
					<mapped param="warning" observer="css2-validator" value="2" />
					<mapped param="warning" observer="css3-validator" value="2" />
					<mapped param="warning" observer="css1-validator" value="2" />
				</value>
			</parameter>
		</parameters>

		<output>
			<group>
				<observation>markup-validator</observation>
			</group>
			<group type="firstPassed">
				<observation>css21-validator</observation>
				<observation>css2-validator</observation>
				<observation>css3-validator</observation>
				<observation>css1-validator</observation>
			</group>
			<group>
				<observation>feed</observation>
			</group>
		</output>
	</task>

	<task id="full-css">
		<routine>
			<exec id="css1" value="css1-validator" type="observation" />
			<exec id="css2" value="css2-validator" type="observation" />
			<exec id="css21" value="css21-validator" type="observation" />
			<exec id="css3" value="css3-validator" type="observation" />
		</routine>

		<parameters>
			<parameter name="warning" type="dropdown" default="no">
				<value name="no">
					<mapped param="warning" observer="css1-validator"
						value="no" />
					<mapped param="warning" observer="css2-validator"
						value="no" />
					<mapped param="warning" observer="css21-validator"
						value="no" />
					<mapped param="warning" observer="css3-validator"
						value="no" />
				</value>
				<value name="0">
					<mapped param="warning" observer="css1-validator"
						value="0" />
					<mapped param="warning" observer="css2-validator"
						value="0" />
					<mapped param="warning" observer="css21-validator"
						value="0" />
					<mapped param="warning" observer="css3-validator"
						value="0" />
				</value>
				<value name="1">
					<mapped param="warning" observer="css1-validator"
						value="1" />
					<mapped param="warning" observer="css2-validator"
						value="1" />
					<mapped param="warning" observer="css21-validator"
						value="1" />
					<mapped param="warning" observer="css3-validator"
						value="1" />
				</value>
				<value name="2">
					<mapped param="warning" observer="css1-validator"
						value="2" />
					<mapped param="warning" observer="css2-validator"
						value="2" />
					<mapped param="warning" observer="css21-validator"
						value="2" />
					<mapped param="warning" observer="css3-validator"
						value="2" />
				</value>
			</parameter>

			<parameter name="usermedium" type="dropdown"
				default="all">
				<value name="all">
					<mapped param="usermedium" observer="css1-validator"
						value="all" />
					<mapped param="usermedium" observer="css2-validator"
						value="all" />
					<mapped param="usermedium"
						observer="css21-validator" value="all" />
					<mapped param="usermedium" observer="css3-validator"
						value="all" />
				</value>
				<value name="aural">
					<mapped param="usermedium" observer="css1-validator"
						value="aural" />
					<mapped param="usermedium" observer="css2-validator"
						value="aural" />
					<mapped param="usermedium"
						observer="css21-validator" value="aural" />
					<mapped param="usermedium" observer="css3-validator"
						value="aural" />
				</value>
				<value name="braille">
					<mapped param="usermedium" observer="css1-validator"
						value="braille" />
					<mapped param="usermedium" observer="css2-validator"
						value="braille" />
					<mapped param="usermedium"
						observer="css21-validator" value="braille" />
					<mapped param="usermedium" observer="css3-validator"
						value="braille" />
				</value>
				<value name="embossed">
					<mapped param="usermedium" observer="css1-validator"
						value="embossed" />
					<mapped param="usermedium" observer="css2-validator"
						value="embossed" />
					<mapped param="usermedium"
						observer="css21-validator" value="embossed" />
					<mapped param="usermedium" observer="css3-validator"
						value="embossed" />
				</value>
				<value name="handheld">
					<mapped param="usermedium" observer="css1-validator"
						value="handheld" />
					<mapped param="usermedium" observer="css2-validator"
						value="handheld" />
					<mapped param="usermedium"
						observer="css21-validator" value="handheld" />
					<mapped param="usermedium" observer="css3-validator"
						value="handheld" />
				</value>
				<value name="print">
					<mapped param="usermedium" observer="css1-validator"
						value="print" />
					<mapped param="usermedium" observer="css2-validator"
						value="print" />
					<mapped param="usermedium"
						observer="css21-validator" value="print" />
					<mapped param="usermedium" observer="css3-validator"
						value="print" />
				</value>
				<value name="projection">
					<mapped param="usermedium" observer="css1-validator"
						value="projection" />
					<mapped param="usermedium" observer="css2-validator"
						value="projection" />
					<mapped param="usermedium"
						observer="css21-validator" value="projection" />
					<mapped param="usermedium" observer="css3-validator"
						value="projection" />
				</value>
				<value name="screen">
					<mapped param="usermedium" observer="css1-validator"
						value="screen" />
					<mapped param="usermedium" observer="css2-validator"
						value="screen" />
					<mapped param="usermedium"
						observer="css21-validator" value="screen" />
					<mapped param="usermedium" observer="css3-validator"
						value="screen" />
				</value>
				<value name="tty">
					<mapped param="usermedium" observer="css1-validator"
						value="tty" />
					<mapped param="usermedium" observer="css2-validator"
						value="tty" />
					<mapped param="usermedium"
						observer="css21-validator" value="tty" />
					<mapped param="usermedium" observer="css3-validator"
						value="tty" />
				</value>
				<value name="tv">
					<mapped param="usermedium" observer="css1-validator"
						value="tv" />
					<mapped param="usermedium" observer="css2-validator"
						value="tv" />
					<mapped param="usermedium"
						observer="css21-validator" value="tv" />
					<mapped param="usermedium" observer="css3-validator"
						value="tv" />
				</value>
				<value name="presentation">
					<mapped param="usermedium" observer="css1-validator"
						value="presentation" />
					<mapped param="usermedium" observer="css2-validator"
						value="presentation" />
					<mapped param="usermedium"
						observer="css21-validator" value="presentation" />
					<mapped param="usermedium" observer="css3-validator"
						value="presentation" />
				</value>
			</parameter>
		</parameters>

		<output>
			<group>
				<observation>css21-validator</observation>
				<observation>css2-validator</observation>
				<observation>css3-validator</observation>
				<observation>css1-validator</observation>
			</group>
		</output>
	</task>

	<task id="mobileok">
		<routine>
			<exec id="mobileok" value="mobileok" type="observation" />
		</routine>

		<parameters>
		</parameters>

		<output>
			<group>
				<observation>mobileok</observation>
			</group>
		</output>
	</task>

	<task id="custom">
		<conds>
			<cond id="param_css" result="passed" type="parameter" parameter="tests">
				<value>css-validator</value>
			</cond>
			<cond id="param_html" result="passed" type="parameter" parameter="tests">
				<value>markup-validator</value>
			</cond>
			<cond id="param_appc" result="passed" type="parameter" parameter="tests">
				<value>appc-checker</value>
			</cond>
			<cond id="param_mobile" result="passed" type="parameter" parameter="tests">
				<value>mobileok</value>
			</cond>
		</conds>

		<routine>
			<if test="param_html">
				<then><exec id="markup" value="markup-validator" type="observation" /></then>
			</if>
			<if test="param_css">
				<then><exec id="css" value="css-validator" type="observation" /></then>
			</if>
			<if test="param_mobile">
				<then><exec id="mobileok" value="mobileok" type="observation" /></then>
			</if>
			<if test="param_appc">
				<then><exec id="appc" value="appc-checker" type="observation" /></then>
			</if>
		</routine>

		<parameters>
			<parameter name="tests" type="checkboxlist" default="" ui="simple">
				<value name="markup-validator"></value>
				<value name="css-validator"></value>
				<value name="appc-checker"></value>
        		<value name="mobileok"></value>
			</parameter>
			<parameter name="profile" type="dropdown" ui="advanced" observer="css-validator" default="css21"/>
			<parameter name="warning" type="dropdown" ui="advanced" observer="css-validator" default="2"/>
			<parameter name="usermedium" type="dropdown" ui="advanced" observer="css-validator" default="screen"/>
		</parameters>

		<output>
			<group>
				<observation>markup-validator</observation>
				<observation>appc-checker</observation>
				<observation>css-validator</observation>
        		<observation>mobileok</observation>
			</group>
		</output>
	</task>

	<task id="cssval2010">
		<routine>
			<exec id="cssval2010" value="cssval2010" type="observation" />
		</routine>

		<parameters>
		</parameters>

		<output>
			<group>
